---
  - name: stop {{ service_name }}
    systemd:
      name: "{{ service_name }}"
      state: stopped
    listen: stop {{ service_name }}

  - name: start {{ service_name }}
    systemd:
      name: "{{ service_name }}"
      state: started
      enabled: yes
    listen: start {{ service_name }}

  - name: restart {{ service_name }}
    systemd:
      name: "{{ service_name }}"
      state: restarted
    listen: restart {{ service_name }}
