---
- name: add mongodb-org-3.4 repo
  yum_repository:
    name: mongodb-org-3.4
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/$basearch/
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc
    gpgcheck: yes
    state: present

- name: install mongodb rpm package
  yum:
    name: mongodb-org
    state: installed
  notify: stop mongod
