---
  - name: set autotrader target version (if defined)
    set_fact:
      atversion: "{{ at_target_version }}"
    when: at_target_version is defined

  - name: set autotrader target version to latest periotheus minor version {{ ansible_local.pt_version.major }}.{{ ansible_local.pt_version.minor }}
    set_fact:
      atversion: "{{ ansible_local.pt_version.major }}.{{ ansible_local.pt_version.minor }}.*"
    when: at_target_version is not defined

  - name: update autotrader packages to {{ atversion }}
    yum:
      name: "autotrader_core-{{ atversion }},autotrader_lib-{{ atversion }},autotrader_adapter-{{ atversion }},autotrader_guard-{{ atversion }},autotrader_rest-{{ atversion }},autotrader_periotheus-{{ atversion }}"
      state: latest
      enablerepo: vtse-testing,autotrader

  - name: update connection manager packages to {{ atversion }}
    yum:
      name: "epex_conmgr-{{ atversion }}"
      state: latest
      enablerepo: vtse-testing,autotrader
    when: autotrader_exchange == "epex"
